### ISSUE TITLE
Bug in adminhtml config

### ISSUE THREAD

**Issue by burntblark** [tawk/tawk-magento#1]
I installed Tawk on our testing server and we could not view System > Permission > Role page. Comes up with an error saying cannot find class Mage_Livechat_Helper_Data. This error is usually occur when the module does not have a help Data class. On checking for a module named "livechat" I could not find it. I eventually saw that in the Acl section of your adminhtml.xml config, you used the module named "livechat" when your module name is actually "tawkwidget." Changing this to "tawkwidget" fixed the issue. Just letting you know.

**Comment by pyhrus** [comment]
Thank you for reporting. This issue has been fixed.
